config/routes.rb
Rails.application.routes.draw do
  resources :fish
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  # You can have the root of your site routed with "root"
  root 'visitors#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/fish.rb
class Fish < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :fish
  
	def self.create_with_omniauth(auth)
	  create! do |user|
	    user.provider = auth["provider"]
	    user.uid = auth["uid"]
	    user.name = auth["info"]["name"]
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

	private

	def current_user
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
end

app/controllers/fish_controller.rb
class FishController < ApplicationController
  before_action :set_fish, only: [:show, :edit, :update, :destroy]

  # GET /fish
  # GET /fish.json
  def index
    @fish = Fish.all
  end

  # GET /fish/1
  # GET /fish/1.json
  def show
  end

  # GET /fish/new
  def new
    @fish = Fish.new
  end

  # GET /fish/1/edit
  def edit
  end

  # POST /fish
  # POST /fish.json
  def create
    @fish = Fish.new(fish_params)
    byebug
    respond_to do |format|
      if @fish.save
        format.html { redirect_to @fish, notice: 'Fish was successfully created.' }
        format.json { render :show, status: :created, location: @fish }
      else
        format.html { render :new }
        format.json { render json: @fish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fish/1
  # PATCH/PUT /fish/1.json
  def update
    respond_to do |format|
      if @fish.update(fish_params)
        format.html { redirect_to @fish, notice: 'Fish was successfully updated.' }
        format.json { render :show, status: :ok, location: @fish }
      else
        format.html { render :edit }
        format.json { render json: @fish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fish/1
  # DELETE /fish/1.json
  def destroy
    @fish.destroy
    respond_to do |format|
      format.html { redirect_to fish_index_url, notice: 'Fish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fish
      @fish = Fish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fish_params
      params.require(:fish).permit(:user_id, :name, :goal, :state, :growth)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
	  auth = request.env["omniauth.auth"]
	  user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
	  session[:user_id] = user.id
	  redirect_to root_url, :notice => "Signed in!"
	end

	def destroy
	  session[:user_id] = nil
	  redirect_to root_url, :notice => "Signed out!"
	end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fish_helper.rb
module FishHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/fish/_form.html.erb
<%= form_for(@fish) do |f| %>
  <% if @fish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fish.errors.count, "error") %> prohibited this fish from being saved:</h2>

      <ul>
      <% @fish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= form_for(@fish) do |f| %>
  <%= f.error_notification %>
  
  <div class="form-inputs">
   <%= f.label :name %>:
   <%= f.text_field :name %><br>
  </div>

  <div class="form-inputs">
   <%= f.label :mission %>:
   <%= f.text_field :mission %><br>
  </div>

  <div class="form-inputs">
   <%= f.label :start_time %>:
   <%= f.time_select :start_time %><br>
  </div>

  <div class="form-inputs">
   <%= f.label :end_time %>:
   <%= f.time_select :end_time %><br>
  </div>

   <div class="form-inputs">
   <%= f.label :date %>:
   <%= f.date_select :date %><br>
  </div>

  <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="form-actions"> 
  <%= f.submit type: 'submit'%><br>
  </div>
  
  <% end %>

app/views/fish/edit.html.erb
<h1>Editing Fish</h1>

<%= render 'form' %>

<%= link_to 'Show', @fish %> |
<%= link_to 'Back', fish_index_path %>

app/views/fish/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Fish</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fish.each do |fish| %>
      <tr>
        <td><%= link_to 'Show', fish %></td>
        <td><%= link_to 'Edit', edit_fish_path(fish) %></td>
        <td><%= link_to 'Destroy', fish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fish', new_fish_path %>

app/views/fish/new.html.erb
<h1>New Fish</h1>

<%= render 'form' %>

<%= link_to 'Back', fish_index_path %>

app/views/fish/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_fish_path(@fish) %> |
<%= link_to 'Back', fish_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Day21</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" type="css/text" href="/css/application.css">
  <script src="/js/application.js" type="javascript"></script> 
  <script   src="https://code.jquery.com/ui/1.12.0-rc.2/jquery-ui.min.js"   integrity="sha256-55Jz3pBCF8z9jBO1qQ7cIf0L+neuPTD1u7Ytzrp2dqo="   crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  Welcome <%= current_user.name %>!
  <%= link_to "Sign Out", signout_path %>
<% else %>
  <%= link_to "Sign in with Facebook", "/auth/facebook" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/visitors/index.html.erb
<div id='table'>
  <div class="add"></div>
  <div class="feed"></div>
</div>
<div class='tank'></div>
<div id='cover'></div>
<div class='tank2'>
  <div class="ship"></div>
</div>
<div class="cup"></div>
<div id='cover2'></div>
 